### ISSUE TITLE
[QUESTION] Game Data Resources Source?

### ISSUE THREAD

**Issue by kiraio-moe** [Tualin14/ba2wall#1]
Hi, @Tualin14.

I already forked this, but I can't find any Game Data `0Data` source to work with in Unity. Does it same with 'Material Data' in https://github.com/Tualin14/ArisStudio ?

**Comment by Tualin14** [comment]
Yes, they are the same, but it doesn't update with the game update.

By the way. I've been having the idea of removing this link and letting users get the material by their own ways.
For example, use this project [blue-archive-jp-assets-downloader](https://github.com/xiongnemo/blue-archive-jp-assets-downloader)

I wanted to find a balance between copyright and ease of use. That's why I added the load command instead of packing it into the program.

**Comment by Tualin14** [comment]
Oh, sorry this is a different project. Orz
The material needs to be obtained by yourself.

This is the project I did to test spine runs before ArisStudio, it was very imperfect and was not continued to be maintained.

**Comment by kiraio-moe** [comment]
> By the way. I've been having the idea of removing this link and letting users get the material by their own ways. For example, use this project [blue-archive-jp-assets-downloader](https://github.com/xiongnemo/blue-archive-jp-assets-downloader)

Well, i did it my self everytime. Even i have downloaded the game data from the link you have provided, I still download the original game data and extract it to find interesting stuff or to check if there's any missing data.

> I wanted to find a balance between copyright and ease of use. That's why I added the load command instead of packing it into the program.

Yes, adding someone work (especially companies) that have copyright to your project is risky. Even it's a fair use.
Many developers try to mitigate this by separating their work with copyrighted stuff or by putting a big DISCLAIMER.

> The material needs to be obtained by yourself.

Okay, I can do it my self. From what I've read in the README, it's requires:

- Character voice (check)
- BGM (check)
- Settings.json (just copy paste from readme)

and lastly `the rest of the material`. I don't know what it contains. Can you tell me?
(I have not yet checking the source code, so I don't know what was requested XD )
Also, the Spine 2D asset (Spr) is same as used during dialogue?

**Comment by Tualin14** [comment]
Bone settings are used to place pat and look trigger areas by left and right eye, halo, and neck coordinates. But the material files are not uniformly named, such as neck, Neck_Root, neck_root, neck_rot, neck_01… so I provide a way to print the names of all the bones and let the user set them up themselves.

Bg settings is for yuzu or hoshino, their backgrounds are also spine files, so both spine files need to be loaded at the same time.

This is a link to the project results https://steamcommunity.com/sharedfiles/filedetails/?id=2902819722
need Wall Engine（I've been very busy lately and have been away from my computer for the past few days. So I can only give you a link. Sorry orz）

**Comment by kiraio-moe** [comment]
> Bone settings are used to place pat and look trigger areas by left and right eye, halo, and neck coordinates. But the material files are not uniformly named, such as neck, Neck_Root, neck_root, neck_rot, neck_01… so I provide a way to print the names of all the bones and let the user set them up themselves.
> 
> Bg settings is for yuzu or hoshino, their backgrounds are also spine files, so both spine files need to be loaded at the same time.

Thanks for explaining :)

> This is a link to the project results https://steamcommunity.com/sharedfiles/filedetails/?id=2902819722 need Wall Engine（I've been very busy lately and have been away from my computer for the past few days. So I can only give you a link. Sorry orz)

I have checked this, not yet install it though.
